In [1]:
import numpy as np
import random
from random import uniform

## 1. Creates a 6x6 matrix

In [20]:
A = np.empty((6,6))
random.seed(3227)

for i in range(A.shape[0]):

  for j in range(A.shape[1]):

    A[i][j] = uniform(-5.0,5.0)

print(A)
print(A[1][2])

[[ 2.35547567  4.96666171 -1.47695258 -2.27638073 -4.67834352  0.11385259]
 [ 1.61318452 -0.31804382 -2.24874012 -4.74977162  0.58857954  3.80166227]
 [-2.11540132 -3.10518602  4.25104872  0.13398253 -2.09210332 -0.37110488]
 [ 1.63513473  2.45689118 -4.24829249  0.12858431  4.05368311 -2.27806961]
 [ 1.52636108  4.00058878 -1.85452332  0.04075467 -4.95569597 -1.09614399]
 [ 4.72744308  0.17842665  4.73255623  0.59257178 -0.38896     3.57186753]]
-2.2487401202855817


## 2. Largest element in a matrix

In [8]:
max = -999
idx = [-1,-1]

for i in range(A.shape[0]):

  for j in range(A.shape[1]):

    if A[i][j] > max :
      max = A[i][j]
      idx = [i,j]

print(max)
print(idx)

## compare with numpy function
print(np.max(A))
print(np.argmax(A))

4.966661705230337
[0, 1]
4.966661705230337
1


## 3. Largest elements row and column

In [9]:
row = np.empty(A.shape[0])

for i in range(A.shape[0]):

  row[i] = -999

  for j in range(A.shape[1]):

    if A[i][j] > row[i] : row[i] = A[i][j]

print(row)

[4.96666171 3.80166227 4.25104872 4.05368311 4.00058878 4.73255623]


In [10]:
column = np.empty(A.shape[1])

for i in range(A.shape[1]):

  column[i] = -999

  for j in range(A.shape[0]):

    if A[j][i] > column[i] : column[i] = A[j][i]

print(column)

[4.72744308 4.96666171 4.73255623 0.59257178 4.05368311 3.80166227]


In [11]:
## compare with np function
print(np.max(A,axis=1))
print(np.max(A,axis=0))

[4.96666171 3.80166227 4.25104872 4.05368311 4.00058878 4.73255623]
[4.72744308 4.96666171 4.73255623 0.59257178 4.05368311 3.80166227]


### Multiply

In [12]:
ans = 0

for i in range(row.shape[0]):

  ans += row[i] * column[i]

print(ans)

## compare with numpy function
row_transpose = row.reshape((1,row.shape[0]))
print(np.matmul(row,column))

99.090305846869
99.090305846869


## 4. Second random 6x6 matrix B

In [21]:
B = np.empty((6,6))

for i in range(B.shape[0]):

  for j in range(B.shape[1]):

    B[i][j] = uniform(-5.0,5.0)

print(B)
print(B[1][2])

[[-3.19197302  1.91841418  4.18066588  0.11838862 -3.0067209  -3.76383611]
 [ 1.62643733  2.61901273  3.40159309 -2.50142078  3.18246325  3.7221252 ]
 [-3.73370714 -3.43010512  4.86691505  2.7000088  -2.73139799  1.78844246]
 [-4.05001654  1.23743539 -1.96129414 -0.01189672 -0.16976215  4.55720341]
 [ 3.21392239  0.38116438 -0.30231828  2.45180612  2.41367396  0.5957307 ]
 [-4.06633069  3.2536773   2.1111402   1.78253961 -2.17970567 -3.33359172]]
3.4015930897807216


In [17]:
C = np.zeros((A.shape[0],B.shape[1]))

for i in range(A.shape[0]):

  for k in range(B.shape[1]):

    for j in range(A.shape[1]):

      C[i][k] += A[i][j] * B[j][k]

print(C)
print(np.matmul(A,B))

[[ -1.48956281 -10.54562951  16.98199889   4.54736608   4.68694038
   18.89714229]
 [ 34.98627804  14.9910183    9.85578445  20.86967043 -41.06815058
  -24.46531159]
 [ -5.77422814  17.89277412  14.35126589 -29.16072885  -6.04628173
   12.57750817]
 [  6.33395826 -16.31065593 -21.7520448   33.28454357  16.91130425
  -11.74906805]
 [-13.46684673 -20.69244786   8.98795754  -1.54638585  18.35296471
   27.97706586]
 [ 17.79157379  14.37704108  31.01551301 -46.29187224 -16.13463514
    2.82052157]]
[[ -1.48956281 -10.54562951  16.98199889   4.54736608   4.68694038
   18.89714229]
 [ 34.98627804  14.9910183    9.85578445  20.86967043 -41.06815058
  -24.46531159]
 [ -5.77422814  17.89277412  14.35126589 -29.16072885  -6.04628173
   12.57750817]
 [  6.33395826 -16.31065593 -21.7520448   33.28454357  16.91130425
  -11.74906805]
 [-13.46684673 -20.69244786   8.98795754  -1.54638585  18.35296471
   27.97706586]
 [ 17.79157379  14.37704108  31.01551301 -46.29187224 -16.13463514
    2.82052157]]


In [19]:
D = np.zeros((B.shape[0],A.shape[1]))

for i in range(B.shape[0]):

  for k in range(A.shape[1]):

    for j in range(B.shape[1]):

      D[i][k] += B[i][j] * A[j][k]

print(np.round(D,decimals=2))
print(np.matmul(B,A))

[[  6.16  -0.5   40.63  -9.9  -47.82  18.98]
 [ -2.39   7.41 -19.73  17.32  16.71 -21.46]
 [ -7.1  -26.    30.2  -15.13 -21.12  26.1 ]
 [ -1.82  -2.67  19.02  31.57 -11.38  -7.6 ]
 [ -7.04  21.76 -53.73 -11.78  16.48 -19.16]
 [-23.58 -15.73 -14.13  -4.91  24.57  -9.51]]
[[  6.15707023  -0.49775452  40.62838541  -9.9033294  -47.82342255
   18.9806817 ]
 [ -2.3936854    7.40826763 -19.73481115  17.32417846  16.70590937
  -21.45914388]
 [ -7.09968427 -26.00069062  30.20254554 -15.12700243 -21.11902105
   26.09676042]
 [ -1.82314886  -2.66838105  19.01640051  31.56830892 -11.37630025
   -7.59556362]
 [ -7.03558991  21.75755392 -53.72608007 -11.77587336  16.48475334
  -19.16202025]
 [-23.58244041 -15.72583101 -14.1314373   -4.91122401  24.56693661
   -9.51019442]]
